-- Convert Patient.status from PostgreSQL native enum to TEXT.
-- Resolves Hibernate/JPA type mismatch: PG rejects `"PatientStatus" = character varying`
-- in WHERE clauses generated by Spring Data derived queries.
ALTER TABLE "Patient" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "Patient" ALTER COLUMN status TYPE TEXT USING status::TEXT;
ALTER TABLE "Patient" ALTER COLUMN status SET DEFAULT 'active';
DROP TYPE IF EXISTS "PatientStatus";
